# Generated by Django 2.2 on 2019-05-06 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputRideInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_first_name', models.CharField(default='first', max_length=200)),
                ('user_last_name', models.CharField(default='last', max_length=200)),
                ('depart_from', models.CharField(choices=[('EWR', 'ewr'), ('PHL', 'phl'), ('JFK', 'jfk'), ('PRINCETON', 'princeton')], default='EWR', max_length=20)),
                ('destination', models.CharField(choices=[('EWR', 'ewr'), ('PHL', 'phl'), ('JFK', 'jfk'), ('PRINCETON', 'princeton')], default='EWR', max_length=20)),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('notes', models.CharField(max_length=500)),
                ('uber', models.BooleanField(default=False)),
                ('lyft', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_status_open', models.BooleanField(default=True)),
                ('joined_rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_ride.InputRideInfo')),
            ],
        ),
    ]
