# Generated by Django 2.2 on 2019-04-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputRideInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('notes', models.CharField(max_length=500)),
                ('uber', models.BooleanField(default=False)),
                ('lyft', models.BooleanField(default=False)),
            ],
        ),
    ]
