# Generated by Django 2.2 on 2019-04-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputrideinfo',
            name='depart_from',
            field=models.CharField(choices=[('EWR', 'ewr'), ('PHL', 'phl'), ('JFK', 'jfk'), ('PRINCETON', 'princeton')], default='EWR', max_length=20),
        ),
        migrations.AddField(
            model_name='inputrideinfo',
            name='destination',
            field=models.CharField(choices=[('EWR', 'ewr'), ('PHL', 'phl'), ('JFK', 'jfk'), ('PRINCETON', 'princeton')], default='EWR', max_length=20),
        ),
    ]
