# Generated by Django 2.2 on 2019-05-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputrideinfo',
            name='ride_status_open',
            field=models.BooleanField(default=True),
        ),
    ]
