# Generated by Django 2.2 on 2019-04-30 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create_ride', '0003_inputrideinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputrideinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
