# Generated by Django 2.2 on 2019-05-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_ride', '0003_inputrideinfo_group_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputrideinfo',
            name='netid',
            field=models.CharField(default='princeton', max_length=200),
        ),
    ]
