# Generated by Django 2.2 on 2019-05-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_ride', '0004_inputrideinfo_netid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputrideinfo',
            name='netid',
        ),
        migrations.AddField(
            model_name='inputrideinfo',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputrideinfo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
