# Generated by Django 2.2 on 2019-05-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_ride', '0004_inputrideinfo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputrideinfo',
            name='user_first_name',
            field=models.CharField(default='first', max_length=200),
        ),
        migrations.AddField(
            model_name='inputrideinfo',
            name='user_last_name',
            field=models.CharField(default='last', max_length=200),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_status_open', models.BooleanField(default=True)),
                ('joined_rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_ride.InputRideInfo')),
            ],
        ),
    ]
