# Generated by Django 2.2 on 2019-05-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_ride', '0007_auto_20190507_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputrideinfo',
            name='depart_from',
            field=models.CharField(choices=[('EWR', 'ewr'), ('PHL', 'phl'), ('JFK', 'jfk'), ('PRINCETON JUNCTION', 'princeton junction'), ('PRINCETON', 'princeton')], default='PRINCETON', max_length=20),
        ),
        migrations.AlterField(
            model_name='inputrideinfo',
            name='destination',
            field=models.CharField(choices=[('EWR', 'ewr'), ('PHL', 'phl'), ('JFK', 'jfk'), ('PRINCETON JUNCTION', 'princeton junction'), ('PRINCETON', 'princeton')], default='PRINCETON', max_length=20),
        ),
    ]
