# Generated by Django 2.2 on 2019-04-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logininfo',
            name='img',
        ),
    ]
