# Generated by Django 2.2 on 2019-05-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_logininfo_netid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logininfo',
            name='netid',
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
