# Generated by Django 2.2 on 2019-04-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_logininfo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
