# Generated by Django 2.2 on 2019-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190507_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='netid',
            field=models.CharField(default='princeton', max_length=200),
        ),
    ]
