# Generated by Django 2.2 on 2019-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_logininfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
