# Generated by Django 2.2 on 2019-05-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_logininfo_netid'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='pic_url',
            field=models.CharField(default='https://campusplan.princeton.edu/sites/campusplan2/files/styles/pwds_media_xxlarge_no_crop/public/banner-2017-campus-plan-28.jpg?itok=QwrGwh5R', max_length=200),
        ),
    ]
