# Generated by Django 2.2 on 2019-05-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_logininfo_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='num_rates',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logininfo',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
