# Generated by Django 2.2 on 2019-05-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190511_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
