# Generated by Django 2.2 on 2019-05-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190512_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='num_rates',
            field=models.IntegerField(default=0),
        ),
    ]
